services:
    app:
        build: .
        container_name: company_api_app
        volumes:
            - .:/var/www
        environment:
            DB_HOST: db
            DB_DATABASE: ${DB_DATABASE:-laravel}
        networks:
            - app-network

    db:
        image: mysql:8.4
        container_name: company_api_db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: company_api_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
